# Generated by Django 3.2.10 on 2022-02-14 22:16

import Auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', Auth.models.MyAccountManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
