# Generated by Django 3.2.10 on 2022-02-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_rename_users_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
